BEGIN;

-- =========================
-- DROP EXISTING TABLES
-- =========================
DROP TABLE IF EXISTS sensor_data CASCADE;
DROP TABLE IF EXISTS role_permission CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS permission CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS buses CASCADE;

-- =========================
-- TABLE: buses
-- =========================
CREATE TABLE buses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model VARCHAR(100) NOT NULL
);

INSERT INTO buses (id, model) VALUES
(2, 'PAZ'),
(1, 'KAMAZ'),
(3, 'NEFAZ');


-- =========================
-- TABLE: permission
-- =========================
CREATE TABLE permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation VARCHAR(255) NOT NULL,
    resource  VARCHAR(255) NOT NULL,
    CONSTRAINT permission_unique_resource_operation UNIQUE (resource, operation)
);

INSERT INTO permission (id, operation, resource) VALUES
(1, 'READ',  'SENSOR'),
(2, 'WRITE', 'SENSOR'),
(3, 'READ',  'BUS'),
(4, 'WRITE', 'BUS');


-- =========================
-- TABLE: role
-- =========================
CREATE TABLE role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

INSERT INTO role (id, name) VALUES
(1, 'USER'),
(2, 'ADMIN');


-- =========================
-- TABLE: role_permission
-- =========================
CREATE TABLE role_permission (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES role(id),
    FOREIGN KEY (permission_id) REFERENCES permission(id)
);

-- USER: только READ
INSERT INTO role_permission (role_id, permission_id) VALUES
(1, 1), -- USER -> READ SENSOR
(1, 3); -- USER -> READ BUS

-- ADMIN: полные права
INSERT INTO role_permission (role_id, permission_id) VALUES
(2, 1), -- ADMIN -> READ SENSOR
(2, 2), -- ADMIN -> WRITE SENSOR
(2, 3), -- ADMIN -> READ BUS
(2, 4); -- ADMIN -> WRITE BUS


-- =========================
-- TABLE: users
-- =========================
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    password VARCHAR(255),
    role_id  BIGINT,
    FOREIGN KEY (role_id) REFERENCES role(id)
);

INSERT INTO users (id, username, password, role_id) VALUES
(
 1,
 'user',
 '$2a$10$JYqx2aTWJsvMFVwHwOJLyu3rGwkJDl4JABxKJoreOnb0WLn6yeqrm',
 1  -- роль USER
),
(
 2,
 'admin',
 '$2a$10$JYqx2aTWJsvMFVwHwOJLyu3rGwkJDl4JABxKJoreOnb0WLn6yeqrm',
 2  -- роль ADMIN
);


-- =========================
-- TABLE: sensor_data
-- =========================
CREATE TABLE sensor_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anomaly BOOLEAN NOT NULL,
    sensor_type VARCHAR(255) NOT NULL,
    "timestamp" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    value DOUBLE PRECISION NOT NULL,
    bus_id BIGINT NOT NULL,
    CONSTRAINT sensor_data_sensor_type_check
        CHECK (sensor_type IN ('ENGINE_TEMP', 'TIRE_PRESSURE', 'FUEL_LEVEL')),
    FOREIGN KEY (bus_id) REFERENCES buses(id)
);

INSERT INTO sensor_data
(id, anomaly, sensor_type, "timestamp", value, bus_id)
VALUES
(1,  false, 'ENGINE_TEMP',   '2025-09-12 08:30:00', 89.5,  1),
(2,  true,  'TIRE_PRESSURE', '2025-09-28 14:20:00', 1.5,   2),
(3,  false, 'FUEL_LEVEL',    '2025-10-05 11:45:00', 52.3,  3),

(4,  true,  'ENGINE_TEMP',   '2025-10-17 16:10:00', 127.8, 1),
(5,  false, 'TIRE_PRESSURE', '2025-10-29 09:05:00', 2.6,   2),
(6,  false, 'FUEL_LEVEL',    '2025-11-03 13:30:00', 41.7,  1),
(7,  true,  'FUEL_LEVEL',    '2025-11-14 18:55:00', 2.8,   3),
(8,  false, 'ENGINE_TEMP',   '2025-11-22 07:40:00', 92.1,  2),
(9,  false, 'TIRE_PRESSURE', '2025-12-01 10:15:00', 2.5,   1),
(10, true,  'ENGINE_TEMP',   '2025-12-18 19:25:00', 130.4, 3),

(11, false, 'FUEL_LEVEL',    '2025-12-27 12:40:00', 36.9,  2),
(12, false, 'TIRE_PRESSURE', '2026-01-04 08:50:00', 2.7,   1),
(13, true,  'TIRE_PRESSURE', '2026-01-11 15:20:00', 1.3,   3),
(14, false, 'ENGINE_TEMP',   '2026-01-20 14:00:00', 90.8,  2),
(15, false, 'FUEL_LEVEL',    '2026-01-30 17:35:00', 48.2,  1);


-- =========================
-- FIX IDENTITY COUNTERS
-- =========================
SELECT setval(pg_get_serial_sequence('buses', 'id'), 3, true);
SELECT setval(pg_get_serial_sequence('permission', 'id'), 4, true);
SELECT setval(pg_get_serial_sequence('role', 'id'), 2, true);
SELECT setval(pg_get_serial_sequence('users', 'id'), 2, true);
SELECT setval(pg_get_serial_sequence('sensor_data', 'id'), 15, true);

COMMIT;