spring:
    profiles:
        active: dev
    application:
        name: SysMon
        version: 1.0.0
---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:postgresql://localhost:5432/bussensors
        username: postgres
        password: 1234
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 20
    
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
    jwt:
        secret: XXX
        access:
            cookie_name: access_token
            duration:
                minute: 5
                second: 300
        refresh:
            cookie_name: refresh_token
            duration:
                day: 7
                second: 604800
server:
    port: 8080
---
spring:
    config:
        activate:
            on-profile: prod
server:
    port: 9001